/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/billing/payment-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiV1BillingPayment-sheet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/likes/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiV1LikesToggle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/likes/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1LikesCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/likes/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1LikesList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/movie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1ProgressMovie"];
        put: operations["putApiV1ProgressMovie"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1ProgressMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/episode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1ProgressEpisode"];
        put: operations["putApiV1ProgressEpisode"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/tv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1ProgressTv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1ProgressAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/progress/mark-all-tv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiV1ProgressMark-all-tv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/getMostPopular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaGetMostPopular"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/getTitleDetails": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaGetTitleDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/getTitleEpisodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaGetTitleEpisodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/getTitleSeasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaGetTitleSeasons"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/getTitlePlot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaGetTitlePlot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/getTopCastCrew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaGetTopCastCrew"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/getFullCastCrew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaGetFullCastCrew"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/getSeasonImages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaGetSeasonImages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaSearch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/getWatchProviders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaGetWatchProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/getMoreLikeThis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaGetMoreLikeThis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/getKeywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaGetKeywords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/getGenres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaGetGenres"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/getRecommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaGetRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/notInterested": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getApiV1MediaNotInterested"];
        put?: never;
        post: operations["postApiV1MediaNotInterested"];
        delete: operations["deleteApiV1MediaNotInterested"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhook/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postApiWebhookStripe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "postApiV1BillingPayment-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    amount: number;
                    currency?: string;
                    connectedAccountId?: string;
                    priceId?: string;
                    plan?: string;
                    annual?: boolean;
                };
                "application/x-www-form-urlencoded": {
                    amount: number;
                    currency?: string;
                    connectedAccountId?: string;
                    priceId?: string;
                    plan?: string;
                    annual?: boolean;
                };
                "multipart/form-data": {
                    amount: number;
                    currency?: string;
                    connectedAccountId?: string;
                    priceId?: string;
                    plan?: string;
                    annual?: boolean;
                };
            };
        };
        responses: never;
    };
    postApiV1LikesToggle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    imdbId: string;
                    /** @enum {string} */
                    mediaType: "movie" | "tv";
                };
                "application/x-www-form-urlencoded": {
                    imdbId: string;
                    /** @enum {string} */
                    mediaType: "movie" | "tv";
                };
                "multipart/form-data": {
                    imdbId: string;
                    /** @enum {string} */
                    mediaType: "movie" | "tv";
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        liked: boolean;
                    };
                };
            };
        };
    };
    getApiV1LikesCheck: {
        parameters: {
            query: {
                imdbId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        liked: boolean;
                    };
                };
            };
        };
    };
    getApiV1LikesList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        likes: {
                            id: number;
                            userId: string;
                            imdbId: string;
                            /** @enum {string} */
                            mediaType: "movie" | "tv";
                            createdAt: Record<string, never> | string | number;
                        }[];
                    };
                };
            };
        };
    };
    getApiV1ProgressMovie: {
        parameters: {
            query: {
                imdbId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        progress: {
                            id: number;
                            userId: string;
                            imdbId: string;
                            isWatched: boolean;
                            updatedAt: Record<string, never> | string | number;
                        } | null;
                    };
                };
            };
        };
    };
    putApiV1ProgressMovie: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    imdbId: string;
                    isWatched?: boolean;
                    title?: string;
                    posterUrl?: string;
                };
                "application/x-www-form-urlencoded": {
                    imdbId: string;
                    isWatched?: boolean;
                    title?: string;
                    posterUrl?: string;
                };
                "multipart/form-data": {
                    imdbId: string;
                    isWatched?: boolean;
                    title?: string;
                    posterUrl?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        progress: {
                            id: number;
                            userId: string;
                            imdbId: string;
                            isWatched: boolean;
                            updatedAt: Record<string, never> | string | number;
                        } | null;
                    };
                };
            };
        };
    };
    getApiV1ProgressMovies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        progress: {
                            id: number;
                            userId: string;
                            imdbId: string;
                            isWatched: boolean;
                            updatedAt: Record<string, never> | string | number;
                        }[];
                    };
                };
            };
        };
    };
    getApiV1ProgressEpisode: {
        parameters: {
            query: {
                imdbId: string;
                seasonNumber: number;
                episodeNumber: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        progress: {
                            id: number;
                            userId: string;
                            imdbId: string;
                            seasonNumber: number;
                            episodeNumber: number;
                            isWatched: boolean;
                            updatedAt: Record<string, never> | string | number;
                        } | null;
                    };
                };
            };
        };
    };
    putApiV1ProgressEpisode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    imdbId: string;
                    seasonNumber: number;
                    episodeNumber: number;
                    isWatched?: boolean;
                    title?: string;
                    posterUrl?: string;
                };
                "application/x-www-form-urlencoded": {
                    imdbId: string;
                    seasonNumber: number;
                    episodeNumber: number;
                    isWatched?: boolean;
                    title?: string;
                    posterUrl?: string;
                };
                "multipart/form-data": {
                    imdbId: string;
                    seasonNumber: number;
                    episodeNumber: number;
                    isWatched?: boolean;
                    title?: string;
                    posterUrl?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        progress: {
                            id: number;
                            userId: string;
                            imdbId: string;
                            seasonNumber: number;
                            episodeNumber: number;
                            isWatched: boolean;
                            updatedAt: Record<string, never> | string | number;
                        } | null;
                    };
                };
            };
        };
    };
    getApiV1ProgressTv: {
        parameters: {
            query: {
                imdbId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        episodes: {
                            id: number;
                            userId: string;
                            imdbId: string;
                            seasonNumber: number;
                            episodeNumber: number;
                            isWatched: boolean;
                            updatedAt: Record<string, never> | string | number;
                        }[];
                        tvShowProgress: {
                            id: number;
                            userId: string;
                            imdbId: string;
                            totalSeasons: number;
                            episodesPerSeason: number[];
                            lastWatchedSeason: number | null;
                            lastWatchedEpisode: number | null;
                            isFullyWatched: boolean;
                            updatedAt: Record<string, never> | string | number;
                        } | null;
                    };
                };
            };
        };
    };
    getApiV1ProgressAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        movies: {
                            id: number;
                            userId: string;
                            imdbId: string;
                            isWatched: boolean;
                            updatedAt: Record<string, never> | string | number;
                            title: string | null;
                            posterUrl: string | null;
                        }[];
                        tvShows: {
                            imdbId: string;
                            title: string | null;
                            posterUrl: string | null;
                            watchedEpisodes: number;
                            totalEpisodes: number;
                            totalSeasons: number | null;
                            lastWatchedSeason: number | null;
                            lastWatchedEpisode: number | null;
                            isFullyWatched: boolean;
                            updatedAt?: Record<string, never> | string | number;
                        }[];
                    };
                };
            };
        };
    };
    "postApiV1ProgressMark-all-tv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    imdbId: string;
                    episodes: {
                        seasonNumber: number;
                        episodeNumber: number;
                    }[];
                    isWatched: boolean;
                    title?: string;
                    posterUrl?: string;
                };
                "application/x-www-form-urlencoded": {
                    imdbId: string;
                    episodes: {
                        seasonNumber: number;
                        episodeNumber: number;
                    }[];
                    isWatched: boolean;
                    title?: string;
                    posterUrl?: string;
                };
                "multipart/form-data": {
                    imdbId: string;
                    episodes: {
                        seasonNumber: number;
                        episodeNumber: number;
                    }[];
                    isWatched: boolean;
                    title?: string;
                    posterUrl?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        progress: {
                            id: number;
                            userId: string;
                            imdbId: string;
                            seasonNumber: number;
                            episodeNumber: number;
                            isWatched: boolean;
                            updatedAt: Record<string, never> | string | number;
                        }[];
                    };
                };
            };
        };
    };
    getApiV1MediaGetMostPopular: {
        parameters: {
            query?: {
                limit?: number;
                mediaType?: "movie" | "tv" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        topMeterTitles: {
                            edges: {
                                node: {
                                    /** @constant */
                                    __typename: "Title";
                                    id: string;
                                    titleText: {
                                        text: string;
                                        isOriginalTitle: boolean;
                                    };
                                    originalTitleText: {
                                        text: string;
                                        isOriginalTitle: boolean;
                                    };
                                    releaseYear: {
                                        /** @constant */
                                        __typename: "YearRange";
                                        year: number;
                                        endYear: number | null;
                                    };
                                    releaseDate: {
                                        /** @constant */
                                        __typename: "ReleaseDate";
                                        month: number | null;
                                        day: number | null;
                                        year: number;
                                        country: {
                                            id: string;
                                        };
                                        restriction: string | null;
                                        attributes: {
                                            id: string;
                                            text: string;
                                        }[];
                                        displayableProperty: {
                                            qualifiersInMarkdownList: string[] | null;
                                        };
                                    };
                                    titleType: {
                                        /** @constant */
                                        __typename: "TitleType";
                                        id: string;
                                        text: string;
                                        categories: {
                                            id: string;
                                            text: string;
                                            value: string;
                                        }[];
                                        canHaveEpisodes: boolean;
                                        isEpisode: boolean;
                                        isSeries: boolean;
                                        displayableProperty: {
                                            value: {
                                                plainText: string;
                                            };
                                        };
                                    };
                                    primaryImage: {
                                        /** @constant */
                                        __typename: "Image";
                                        id: string;
                                        url: string;
                                        height: number;
                                        width: number;
                                    };
                                    meterRanking: {
                                        /** @constant */
                                        __typename: "TitleMeterRanking";
                                        currentRank: number;
                                        rankChange: {
                                            /** @enum {string} */
                                            changeDirection: "UP" | "DOWN" | "FLAT";
                                            difference: number;
                                        };
                                    };
                                };
                            }[];
                        };
                    };
                };
            };
        };
    };
    getApiV1MediaGetTitleDetails: {
        parameters: {
            query: {
                tt: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    getApiV1MediaGetTitleEpisodes: {
        parameters: {
            query: {
                tt: string;
                seasonNumber: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        title: {
                            id: string;
                            episodes: {
                                episodes: {
                                    edges: {
                                        node: {
                                            id: string;
                                            plot?: {
                                                id: string;
                                                plotText: {
                                                    plainText: string;
                                                };
                                            } | null;
                                        };
                                        position: number;
                                    }[];
                                    pageInfo: {
                                        /** @constant */
                                        __typename: "PageInfo";
                                        hasNextPage: boolean;
                                        hasPreviousPage: boolean;
                                        startCursor: string;
                                        endCursor: string;
                                    };
                                    total: number;
                                };
                            };
                        };
                    };
                };
            };
        };
    };
    getApiV1MediaGetTitleSeasons: {
        parameters: {
            query: {
                tt: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        title: {
                            episodes: {
                                displayableSeasons: {
                                    edges: {
                                        node: {
                                            id: string;
                                            season: string;
                                            text: string;
                                        };
                                    }[];
                                    pageInfo: {
                                        /** @constant */
                                        __typename: "PageInfo";
                                        hasNextPage: boolean;
                                        hasPreviousPage: boolean;
                                        startCursor: string;
                                        endCursor: string;
                                    };
                                    total: number;
                                };
                            };
                        };
                    };
                };
            };
        };
    };
    getApiV1MediaGetTitlePlot: {
        parameters: {
            query: {
                tt: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        title: {
                            id: string;
                            plot: {
                                id: string;
                                plotText: {
                                    plainText: string;
                                };
                            } | null;
                            type: {
                                /** @constant */
                                __typename: "TitleType";
                                id: string;
                                text: string;
                                categories: {
                                    id: string;
                                    text: string;
                                    value: string;
                                }[];
                                canHaveEpisodes: boolean;
                                isEpisode: boolean;
                                isSeries: boolean;
                                displayableProperty: {
                                    value: {
                                        plainText: string;
                                    };
                                };
                            };
                        };
                    };
                };
            };
        };
    };
    getApiV1MediaGetTopCastCrew: {
        parameters: {
            query: {
                tt: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        title: {
                            id: string;
                            titleType: {
                                /** @constant */
                                __typename: "TitleType";
                                id: string;
                                text: string;
                                categories: {
                                    id: string;
                                    text: string;
                                    value: string;
                                }[];
                                canHaveEpisodes: boolean;
                                isEpisode: boolean;
                                isSeries: boolean;
                                displayableProperty: {
                                    value: {
                                        plainText: string;
                                    };
                                };
                            };
                            principalCredits: {
                                credits: ({
                                    /** @constant */
                                    __typename: "Crew";
                                } | {
                                    /** @constant */
                                    __typename: "Cast";
                                    characters: {
                                        id: string;
                                        name: string;
                                    }[];
                                    name: {
                                        /** @constant */
                                        __typename: "Name";
                                        id: string;
                                        nameText: {
                                            text: string;
                                        };
                                        primaryImage: {
                                            /** @constant */
                                            __typename: "Image";
                                            id: string;
                                            url: string;
                                            height: number;
                                            width: number;
                                        } | null;
                                    };
                                })[];
                            }[];
                            credits: {
                                /** @constant */
                                __typename: "CreditConnection";
                                edges: {
                                    node: {
                                        /** @constant */
                                        __typename: "Cast";
                                        characters: {
                                            id: string;
                                            name: string;
                                        }[];
                                        name: {
                                            /** @constant */
                                            __typename: "Name";
                                            id: string;
                                            nameText: {
                                                text: string;
                                            };
                                            primaryImage: {
                                                /** @constant */
                                                __typename: "Image";
                                                id: string;
                                                url: string;
                                                height: number;
                                                width: number;
                                            } | null;
                                        };
                                    };
                                }[];
                                total: number;
                            };
                        };
                    };
                };
            };
        };
    };
    getApiV1MediaGetFullCastCrew: {
        parameters: {
            query: {
                tt: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        title: {
                            id?: string;
                            titleType?: {
                                /** @constant */
                                __typename: "TitleType";
                                id: string;
                                text: string;
                                categories: {
                                    id: string;
                                    text: string;
                                    value: string;
                                }[];
                                canHaveEpisodes: boolean;
                                isEpisode: boolean;
                                isSeries: boolean;
                                displayableProperty: {
                                    value: {
                                        plainText: string;
                                    };
                                };
                            };
                            principalCredits?: {
                                credits: ({
                                    /** @constant */
                                    __typename: "Crew";
                                } | {
                                    /** @constant */
                                    __typename: "Cast";
                                    characters: {
                                        id: string;
                                        name: string;
                                    }[];
                                    name: {
                                        /** @constant */
                                        __typename: "Name";
                                        id: string;
                                        nameText: {
                                            text: string;
                                        };
                                        primaryImage: {
                                            /** @constant */
                                            __typename: "Image";
                                            id: string;
                                            url: string;
                                            height: number;
                                            width: number;
                                        } | null;
                                    };
                                })[];
                            }[];
                            credits: {
                                /** @constant */
                                __typename?: "CreditConnection";
                                pageInfo?: {
                                    /** @constant */
                                    __typename: "PageInfo";
                                    hasNextPage: boolean;
                                    hasPreviousPage: boolean;
                                    startCursor: string | null;
                                    endCursor: string | null;
                                };
                                edges: {
                                    node: {
                                        /** @constant */
                                        __typename: "Cast";
                                        characters?: {
                                            id?: string;
                                            name: string;
                                        }[];
                                        name: {
                                            /** @constant */
                                            __typename: "Name";
                                            id: string;
                                            nameText: {
                                                text: string;
                                            };
                                            primaryImage: {
                                                /** @constant */
                                                __typename: "Image";
                                                id: string;
                                                url: string;
                                                height: number;
                                                width: number;
                                            } | null;
                                        };
                                    };
                                }[];
                                total: number;
                            };
                        };
                    };
                };
            };
        };
    };
    getApiV1MediaGetSeasonImages: {
        parameters: {
            query: {
                tt: string;
                seasonNumber: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        posters: {
                            aspect_ratio: number;
                            height: number;
                            iso_3166_1: string | null;
                            iso_639_1: string | null;
                            file_path: string;
                            vote_average: number;
                            vote_count: number;
                            width: number;
                        }[];
                    };
                };
            };
        };
    };
    getApiV1MediaSearch: {
        parameters: {
            query: {
                query: string;
                page: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        page: number;
                        results: ({
                            adult: boolean;
                            backdrop_path: string | null;
                            id: string;
                            title: string;
                            original_language: string;
                            original_title: string;
                            overview: string;
                            poster_path: string | null;
                            /** @constant */
                            media_type: "movie";
                            genre_ids: number[];
                            popularity: number;
                            release_date: string;
                            video: boolean;
                            vote_average: number;
                            vote_count: number;
                        } | {
                            adult: boolean;
                            backdrop_path: string | null;
                            id: string;
                            name: string;
                            original_language: string;
                            original_name: string;
                            overview: string;
                            poster_path: string | null;
                            /** @constant */
                            media_type: "tv";
                            genre_ids: number[];
                            popularity: number;
                            first_air_date: string;
                            vote_average: number;
                            vote_count: number;
                            origin_country: string[];
                        })[];
                        total_pages: number;
                        total_results: number;
                    };
                };
            };
        };
    };
    getApiV1MediaGetWatchProviders: {
        parameters: {
            query: {
                tt: string;
                mediaType: "movie" | "tv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        results: {
                            [key: string]: {
                                link: string;
                                flatrate?: {
                                    logo_path: string;
                                    provider_id: number;
                                    provider_name: string;
                                    display_priority: number;
                                }[];
                                rent?: {
                                    logo_path: string;
                                    provider_id: number;
                                    provider_name: string;
                                    display_priority: number;
                                }[];
                                buy?: {
                                    logo_path: string;
                                    provider_id: number;
                                    provider_name: string;
                                    display_priority: number;
                                }[];
                                ads?: {
                                    logo_path: string;
                                    provider_id: number;
                                    provider_name: string;
                                    display_priority: number;
                                }[];
                            };
                        };
                    };
                };
            };
        };
    };
    getApiV1MediaGetMoreLikeThis: {
        parameters: {
            query: {
                tt: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        title: {
                            moreLikeThisTitles: {
                                edges: {
                                    node: {
                                        id: string;
                                    };
                                }[];
                            };
                        };
                    };
                };
            };
        };
    };
    getApiV1MediaGetKeywords: {
        parameters: {
            query: {
                tt: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        title: {
                            id: string;
                            titleType: {
                                id: string;
                            };
                            keywordItemCategories: {
                                itemCategory: {
                                    id: string;
                                    itemCategoryId: string;
                                    text: string;
                                };
                                keywords: {
                                    /** @constant */
                                    __typename: "TitleKeywordConnection";
                                    total: number;
                                    edges: {
                                        node: {
                                            keyword: {
                                                id: string;
                                                text: {
                                                    text: string;
                                                };
                                                category: {
                                                    id: string;
                                                } | null;
                                            };
                                        };
                                    }[];
                                };
                            }[];
                        };
                    };
                };
            };
        };
    };
    getApiV1MediaGetGenres: {
        parameters: {
            query: {
                tt: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        title: {
                            id: string;
                            titleGenres: {
                                genres: {
                                    genre: {
                                        genreId: string;
                                        text: string;
                                    };
                                }[];
                            };
                        };
                    };
                };
            };
        };
    };
    getApiV1MediaGetRecommendations: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sections: {
                            /** @enum {string} */
                            type: "because_you_liked" | "top_genres" | "trending";
                            title: string;
                            subtitle: string;
                            recommendations: {
                                id: string;
                                titleText: {
                                    text: string;
                                };
                                primaryImage: {
                                    url: string;
                                } | null;
                                releaseYear: {
                                    year: number;
                                } | null;
                                titleType: {
                                    id: string;
                                    isSeries: boolean;
                                };
                                score: number;
                                matchedGenres: string[];
                                matchedKeywords: string[];
                                reason: string;
                            }[];
                        }[];
                        topGenres: string[];
                        hasProfile: boolean;
                    };
                };
            };
        };
    };
    getApiV1MediaNotInterested: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        notInterested: string[];
                    };
                };
            };
        };
    };
    postApiV1MediaNotInterested: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    imdbId: string;
                    /** @enum {string} */
                    mediaType: "movie" | "tv";
                };
                "application/x-www-form-urlencoded": {
                    imdbId: string;
                    /** @enum {string} */
                    mediaType: "movie" | "tv";
                };
                "multipart/form-data": {
                    imdbId: string;
                    /** @enum {string} */
                    mediaType: "movie" | "tv";
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    deleteApiV1MediaNotInterested: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    imdbId: string;
                };
                "application/x-www-form-urlencoded": {
                    imdbId: string;
                };
                "multipart/form-data": {
                    imdbId: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    postApiWebhookStripe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
}
